//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//!
//! 对应数据库表 `demo_contact`（联系人表）。

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// 联系人表 Model。
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "demo_contact")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    /// 姓名。
    pub name: String,
    /// 性别。
    pub sex: i8,
    /// 生日。
    pub birthday: DateTime,
    /// 描述。
    pub description: String,
    /// 头像 URL。
    pub avatar: Option<String>,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
