//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//!
//! 对应数据库表 `demo_student`（学生表）。

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// 学生表 Model。
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "demo_student")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    /// 学生姓名。
    pub name: String,
    /// 性别：0-未知, 1-男, 2-女。
    pub sex: i8,
    /// 生日。
    pub birthday: DateTime,
    /// 个人描述。
    pub description: String,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
