//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//!
//! 对应数据库表 `demo_grade`（成绩表）。

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// 成绩表 Model。
///
/// 通过 `student_id` 关联学生，记录科目名称和授课教师。
/// 带有标准审计字段和租户隔离字段。
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "demo_grade")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    /// 主键 ID。
    #[sea_orm(primary_key)]
    pub id: i64,
    /// 学生 ID（关联 `demo_student` 表）。
    pub student_id: i64,
    /// 科目名称。
    pub name: String,
    /// 授课教师。
    pub teacher: String,
    /// 创建人。
    pub creator: Option<String>,
    /// 创建时间。
    pub create_time: DateTime,
    /// 更新人。
    pub updater: Option<String>,
    /// 更新时间。
    pub update_time: DateTime,
    /// 逻辑删除标记。
    pub deleted: bool,
    /// 租户 ID（多租户隔离）。
    pub tenant_id: i64,
}

/// 表关联关系定义（当前为空）。
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

/// ActiveModel 行为实现。
impl ActiveModelBehavior for ActiveModel {}
