//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//!
//! 对应数据库表 `demo_grade`（成绩表）。

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// 成绩表 Model。
///
/// 通过 `student_id` 关联学生。
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "demo_grade")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    /// 学生 ID（外键）。
    pub student_id: i64,
    /// 科目名称。
    pub name: String,
    /// 授课教师。
    pub teacher: String,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
