//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//!
//! 对应数据库表 `demo_sys_user`（系统用户表）。

use crate::enumeration::Gender;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// 系统用户表 Model。
///
/// 包含用户的基本身份信息，如姓名、性别、账号、手机号等。
/// 带有标准审计字段 `creator`、`updater`、`create_time`、`update_time`、
/// 逻辑删除标记 `deleted` 和租户隔离字段 `tenant_id`。
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "demo_sys_user")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    /// 主键 ID。
    #[sea_orm(primary_key)]
    pub id: i64,

    /// 用户姓名。
    pub name: String,

    /// 性别。
    pub gender: Gender,

    /// 账号。
    pub account: String,

    /// 密码（加密存储）。
    pub password: String,

    /// 手机号。
    pub mobile_phone: String,

    /// 生日。
    pub birthday: Date,

    /// 是否启用。
    pub enabled: bool,

    /// 创建人。
    pub creator: Option<String>,

    /// 创建时间。
    pub create_time: DateTime,

    /// 更新人。
    pub updater: Option<String>,

    /// 更新时间。
    pub update_time: DateTime,

    /// 逻辑删除标记。
    pub deleted: bool,

    /// 租户 ID（多租户隔离）。
    pub tenant_id: i64,
}

/// 表关联关系定义（当前为空，后续可补充外键关联）。
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
