//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//!
//! 对应数据库表 `demo_category`（分类表）。

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// 分类表 Model。
///
/// 支持层级分类结构（通过 `parent_id` 自引用）。
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "demo_category")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    /// 分类名称。
    pub name: String,
    /// 父分类 ID，0 表示顶级分类。
    pub parent_id: i64,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
