//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod demo_category;
pub mod demo_contact;
pub mod demo_course;
pub mod demo_grade;
pub mod demo_student;
pub mod demo_sys_user;
