//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::demo_category::Entity as DemoCategory;
pub use super::demo_contact::Entity as DemoContact;
pub use super::demo_course::Entity as DemoCourse;
pub use super::demo_grade::Entity as DemoGrade;
pub use super::demo_student::Entity as DemoStudent;
pub use super::demo_sys_user::Entity as DemoSysUser;
